# Generated by Django 4.1.7 on 2023-03-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='available_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('E_mail', models.CharField(max_length=100)),
                ('ph_no', models.IntegerField(max_length=11)),
                ('subject', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='nearby_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_properties', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('price', models.IntegerField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Selling_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_properties', models.CharField(max_length=40)),
                ('area_name', models.CharField(max_length=40)),
                ('price', models.IntegerField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.rental_properties')),
                ('Sell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.selling_properties')),
                ('available_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.available_properties')),
                ('nearby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.nearby_properties')),
            ],
        ),
        migrations.CreateModel(
            name='Property_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(max_length=40)),
                ('property_description', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('area_sq', models.CharField(max_length=10)),
                ('property_type', models.CharField(max_length=10)),
                ('bathrooms', models.IntegerField(max_length=40)),
                ('other_facilities', models.CharField(max_length=40)),
                ('Rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.rental_properties')),
                ('Sell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.selling_properties')),
            ],
        ),
        migrations.AddField(
            model_name='nearby_properties',
            name='Rent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.rental_properties'),
        ),
        migrations.AddField(
            model_name='nearby_properties',
            name='Sell_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.selling_properties'),
        ),
        migrations.AddField(
            model_name='nearby_properties',
            name='detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.property_details'),
        ),
        migrations.CreateModel(
            name='Future_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.IntegerField(max_length=100)),
                ('increase_by', models.IntegerField(max_length=40)),
                ('decrease_by', models.IntegerField(max_length=40)),
                ('Rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.rental_properties')),
                ('Sell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.selling_properties')),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.property_details')),
            ],
        ),
        migrations.CreateModel(
            name='Current_worth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.IntegerField(max_length=100)),
                ('min_amount', models.IntegerField(max_length=100)),
                ('Rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.rental_properties')),
                ('Sell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.selling_properties')),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.property_details')),
            ],
        ),
        migrations.AddField(
            model_name='available_properties',
            name='Rent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.rental_properties'),
        ),
        migrations.AddField(
            model_name='available_properties',
            name='Sell_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.selling_properties'),
        ),
        migrations.AddField(
            model_name='available_properties',
            name='detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.property_details'),
        ),
    ]
