# Generated by Django 4.1.7 on 2023-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyGuru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_worth',
            name='max_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='current_worth',
            name='min_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ph_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='future_price',
            name='decrease_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='future_price',
            name='increase_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='future_price',
            name='predicted_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental_properties',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='selling_properties',
            name='price',
            field=models.IntegerField(),
        ),
    ]
