# Generated by Django 4.2 on 2023-04-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyGuru', '0003_remove_property_details_other_facilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('Property_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('propertylink_href', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area_sq', models.CharField(blank=True, max_length=10, null=True)),
                ('property_description', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=30, null=True)),
                ('amenities', models.CharField(blank=True, max_length=300, null=True)),
                ('property_type', models.CharField(blank=True, max_length=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('image_src', models.CharField(blank=True, max_length=400, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nearby_properties',
            name='Rent_id',
        ),
        migrations.RemoveField(
            model_name='nearby_properties',
            name='Sell_id',
        ),
        migrations.RemoveField(
            model_name='nearby_properties',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='property_details',
            name='Rent_id',
        ),
        migrations.RemoveField(
            model_name='property_details',
            name='Sell_id',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='Rent_id',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='Sell_id',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='available_id',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='nearby_id',
        ),
        migrations.RemoveField(
            model_name='current_worth',
            name='Rent_id',
        ),
        migrations.RemoveField(
            model_name='current_worth',
            name='Sell_id',
        ),
        migrations.RemoveField(
            model_name='current_worth',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='future_price',
            name='Rent_id',
        ),
        migrations.RemoveField(
            model_name='future_price',
            name='Sell_id',
        ),
        migrations.RemoveField(
            model_name='future_price',
            name='detail_id',
        ),
        migrations.DeleteModel(
            name='available_properties',
        ),
        migrations.DeleteModel(
            name='nearby_properties',
        ),
        migrations.DeleteModel(
            name='Property_details',
        ),
        migrations.DeleteModel(
            name='recommendations',
        ),
        migrations.DeleteModel(
            name='Rental_Properties',
        ),
        migrations.DeleteModel(
            name='Selling_Properties',
        ),
        migrations.AddField(
            model_name='current_worth',
            name='p_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.properties'),
        ),
        migrations.AddField(
            model_name='future_price',
            name='p_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PropertyGuru.properties'),
        ),
    ]
