# Generated by Django 4.2 on 2023-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyGuru', '0004_properties_remove_nearby_properties_rent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
